measurevaluenotmoney
wonas2ds3sp
email: your-email@domain.c
Sound money.
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
wonas2ds3sp

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
